console.time("Your Code Took");
console.log("Hello Villain");
console.log(4+34);
console.log([34,45,67]);
console.log({villain:"saif",age:'21',cgpa:'9.1'});
console.table({villain:"saif",age:'21',cgpa:'9.1'});
console.warn("This is a Warning");
// console.clear();
console.timeEnd("Your Code Took");
console.assert(789<190,'Age>190 isnt possible');
console.error("Error Here!!");